# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: containerd-shim-remoteproc-v1
    main: ./cmd/containerd-shim-remoteproc-v1
    binary: containerd-shim-remoteproc-v1
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
  - id: remoteproc-runtime
    main: ./cmd/remoteproc-runtime
    binary: remoteproc-runtime
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "remoteproc-runtime_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - docs/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^refactor:"
