name: Black Duck Scan

on:
  push:
    branches: [main]
    tags: ["*"]

concurrency:
  group: blackduck-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  scan:
    name: Black Duck Scan
    runs-on: ubuntu-latest
    env:
      DETECT_PROJECT_NAME: DEML-remoteproc-runtime
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set repository reference
        run: |
          ver_to_reference="${{ github.ref_name }}"
          ver_to_reference="${ver_to_reference//\//-}"
          echo "DETECT_PROJECT_VERSION_NAME=$ver_to_reference" >> $GITHUB_ENV
          echo "::notice title=Black Duck target::${{ env.DETECT_PROJECT_NAME }} / $ver_to_reference"

      - name: Black Duck Security Scan
        uses: blackduck-inc/black-duck-security-scan@b6f87e0cec75fc586a22ce6e076e3b9d691b685a # v2.5.0
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_scan_full: true
          blackducksca_waitForScan: true
          blackducksca_scan_failure_severities: BLOCKER,CRITICAL,MAJOR
          blackducksca_prComment_enabled: false
